import { View, Text, Share, Platform } from "react-native";
import { MaterialIcons } from "@expo/vector-icons";
import * as Haptics from "expo-haptics";
import type { Trip } from "../types/trip";
import { CATEGORY_LABELS, type ExpenseCategory } from "../types/expense";
import { BigButton } from "./BigButton";
import { MoneyPill } from "./MoneyPill";
import { colors } from "../theme/tokens";

interface ShareCardProps {
  trip: Trip;
}

function formatDate(iso: string): string {
  const d = new Date(iso);
  return d.toLocaleDateString("hi-IN", { day: "numeric", month: "short", year: "numeric" });
}

function buildShareText(trip: Trip): string {
  const lines = [
    `🚛 *MaalSaathi Trip Summary*`,
    ``,
    `📍 ${trip.origin} → ${trip.destination}`,
    `🚚 ${trip.truckRegistration}`,
    trip.cargoType ? `📦 ${trip.cargoType}` : null,
    `📅 ${formatDate(trip.startedAt)}${trip.completedAt ? ` - ${formatDate(trip.completedAt)}` : ""}`,
    ``,
    `💰 *Bhada:* ₹${trip.freightAmount.toLocaleString("en-IN")}`,
  ];

  if (trip.expenses.length > 0) {
    lines.push(`📊 *Kharche:*`);
    const byCategory = new Map<string, number>();
    for (const exp of trip.expenses) {
      const label = CATEGORY_LABELS[exp.category as ExpenseCategory] || exp.category;
      byCategory.set(label, (byCategory.get(label) || 0) + exp.amount);
    }
    for (const [cat, amt] of byCategory) {
      lines.push(`  • ${cat}: ₹${amt.toLocaleString("en-IN")}`);
    }
    lines.push(`  *Total Kharcha:* ₹${trip.totalExpenses.toLocaleString("en-IN")}`);
  }

  lines.push(``);
  const profit = trip.netProfit;
  lines.push(
    profit >= 0
      ? `✅ *Fayda:* ₹${profit.toLocaleString("en-IN")}`
      : `❌ *Nuksan:* ₹${Math.abs(profit).toLocaleString("en-IN")}`,
  );
  lines.push(``);
  lines.push(`_Generated by MaalSaathi_`);

  return lines.filter((l) => l !== null).join("\n");
}

export function ShareCard({ trip }: ShareCardProps) {
  const handleShare = async () => {
    Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
    const text = buildShareText(trip);
    await Share.share(
      { message: text },
      Platform.OS === "android" ? { dialogTitle: "Trip Summary Share Karo" } : {},
    );
  };

  return (
    <View className="mx-4 rounded-card border border-border bg-surface-elevated p-5">
      <View className="mb-4 flex-row items-center gap-2">
        <MaterialIcons name="local-shipping" size={22} color={colors.textSecondary} />
        <Text className="flex-1 text-lg font-bold text-text-primary">
          Trip Summary
        </Text>
        <Text className="text-sm text-text-secondary">
          {formatDate(trip.startedAt)}
        </Text>
      </View>

      <View className="mb-4 flex-row items-center gap-2">
        <Text className="text-body font-semibold text-text-primary">
          {trip.origin}
        </Text>
        <MaterialIcons name="arrow-forward" size={16} color={colors.textSecondary} />
        <Text className="text-body font-semibold text-text-primary">
          {trip.destination}
        </Text>
      </View>

      <View className="mb-4 flex-row justify-between rounded-button bg-dark px-4 py-3">
        <MoneyPill amount={trip.freightAmount} label="Bhada" size="sm" neutral showSign={false} />
        <MoneyPill amount={trip.totalExpenses} label="Kharcha" size="sm" neutral showSign={false} />
        <MoneyPill amount={trip.netProfit} label="Fayda" size="sm" />
      </View>

      {trip.expenses.length > 0 && (
        <View className="mb-4 gap-2">
          {trip.expenses.slice(0, 5).map((exp) => (
            <View key={exp._id} className="flex-row items-center justify-between">
              <Text className="text-sm text-text-secondary">
                {CATEGORY_LABELS[exp.category as ExpenseCategory] || exp.category}
              </Text>
              <Text className="text-sm font-medium text-text-primary">
                ₹{exp.amount.toLocaleString("en-IN")}
              </Text>
            </View>
          ))}
          {trip.expenses.length > 5 && (
            <Text className="text-sm text-text-secondary">
              +{trip.expenses.length - 5} aur kharche
            </Text>
          )}
        </View>
      )}

      <BigButton
        title="WhatsApp pe Share Karo"
        onPress={handleShare}
        variant="primary"
        icon="share"
      />
    </View>
  );
}
